var annotated_dup =
[
    [ "ncine", null, [
      [ "LuaUtils", null, [
        [ "RunInfo", "classncine_1_1_lua_utils_1_1_run_info.html", "classncine_1_1_lua_utils_1_1_run_info" ]
      ] ],
      [ "AndroidApplication", "classncine_1_1_android_application.html", "classncine_1_1_android_application" ],
      [ "AnimatedSprite", "classncine_1_1_animated_sprite.html", "classncine_1_1_animated_sprite" ],
      [ "AppConfiguration", "classncine_1_1_app_configuration.html", "classncine_1_1_app_configuration" ],
      [ "Application", "classncine_1_1_application.html", "classncine_1_1_application" ],
      [ "AssetFile", "classncine_1_1_asset_file.html", "classncine_1_1_asset_file" ],
      [ "AudioBuffer", "classncine_1_1_audio_buffer.html", "classncine_1_1_audio_buffer" ],
      [ "AudioBufferPlayer", "classncine_1_1_audio_buffer_player.html", "classncine_1_1_audio_buffer_player" ],
      [ "AudioEffect", "classncine_1_1_audio_effect.html", "classncine_1_1_audio_effect" ],
      [ "AudioEffectProperties", "classncine_1_1_audio_effect_properties.html", "classncine_1_1_audio_effect_properties" ],
      [ "AudioEffectSlot", "classncine_1_1_audio_effect_slot.html", "classncine_1_1_audio_effect_slot" ],
      [ "AudioFilter", "classncine_1_1_audio_filter.html", "classncine_1_1_audio_filter" ],
      [ "AudioStream", "classncine_1_1_audio_stream.html", "classncine_1_1_audio_stream" ],
      [ "AudioStreamPlayer", "classncine_1_1_audio_stream_player.html", "classncine_1_1_audio_stream_player" ],
      [ "BaseSprite", "classncine_1_1_base_sprite.html", "classncine_1_1_base_sprite" ],
      [ "Camera", "classncine_1_1_camera.html", "classncine_1_1_camera" ],
      [ "Color", "classncine_1_1_color.html", "classncine_1_1_color" ],
      [ "ColorAffector", "classncine_1_1_color_affector.html", "classncine_1_1_color_affector" ],
      [ "Colorf", "classncine_1_1_colorf.html", "classncine_1_1_colorf" ],
      [ "ColorHdr", "classncine_1_1_color_hdr.html", "classncine_1_1_color_hdr" ],
      [ "CountSplitter", "classncine_1_1_count_splitter.html", null ],
      [ "Crashpad", "classncine_1_1_crashpad.html", null ],
      [ "DataSizeSplitter", "classncine_1_1_data_size_splitter.html", null ],
      [ "DisplayMode", "classncine_1_1_display_mode.html", "classncine_1_1_display_mode" ],
      [ "DrawableNode", "classncine_1_1_drawable_node.html", "classncine_1_1_drawable_node" ],
      [ "DropEvent", "classncine_1_1_drop_event.html", null ],
      [ "EmscriptenLocalFile", "classncine_1_1_emscripten_local_file.html", "classncine_1_1_emscripten_local_file" ],
      [ "FileSystem", "classncine_1_1_file_system.html", "classncine_1_1_file_system" ],
      [ "Font", "classncine_1_1_font.html", "classncine_1_1_font" ],
      [ "Hash64", "classncine_1_1_hash64.html", "classncine_1_1_hash64" ],
      [ "HatState", "structncine_1_1_hat_state.html", null ],
      [ "IAppEventHandler", "classncine_1_1_i_app_event_handler.html", "classncine_1_1_i_app_event_handler" ],
      [ "IAudioDevice", "classncine_1_1_i_audio_device.html", "classncine_1_1_i_audio_device" ],
      [ "IAudioPlayer", "classncine_1_1_i_audio_player.html", "classncine_1_1_i_audio_player" ],
      [ "IDebugOverlay", "classncine_1_1_i_debug_overlay.html", "classncine_1_1_i_debug_overlay" ],
      [ "IFile", "classncine_1_1_i_file.html", "classncine_1_1_i_file" ],
      [ "IFrameTimer", "classncine_1_1_i_frame_timer.html", "classncine_1_1_i_frame_timer" ],
      [ "IGfxCapabilities", "classncine_1_1_i_gfx_capabilities.html", "classncine_1_1_i_gfx_capabilities" ],
      [ "IGfxDevice", "classncine_1_1_i_gfx_device.html", "classncine_1_1_i_gfx_device" ],
      [ "IImageSaver", "classncine_1_1_i_image_saver.html", "classncine_1_1_i_image_saver" ],
      [ "IIndexer", "classncine_1_1_i_indexer.html", "classncine_1_1_i_indexer" ],
      [ "IInputEventHandler", "classncine_1_1_i_input_event_handler.html", "classncine_1_1_i_input_event_handler" ],
      [ "IInputManager", "classncine_1_1_i_input_manager.html", "classncine_1_1_i_input_manager" ],
      [ "IJobSystem", "classncine_1_1_i_job_system.html", "classncine_1_1_i_job_system" ],
      [ "ILogger", "classncine_1_1_i_logger.html", "classncine_1_1_i_logger" ],
      [ "ImageSaverPng", "classncine_1_1_image_saver_png.html", "classncine_1_1_image_saver_png" ],
      [ "ImageSaverWebP", "classncine_1_1_image_saver_web_p.html", "classncine_1_1_image_saver_web_p" ],
      [ "JobHandle", "classncine_1_1_job_handle.html", "classncine_1_1_job_handle" ],
      [ "JobStatistics", "classncine_1_1_job_statistics.html", "classncine_1_1_job_statistics" ],
      [ "JoyAxisEvent", "classncine_1_1_joy_axis_event.html", "classncine_1_1_joy_axis_event" ],
      [ "JoyButtonEvent", "classncine_1_1_joy_button_event.html", "classncine_1_1_joy_button_event" ],
      [ "JoyConnectionEvent", "classncine_1_1_joy_connection_event.html", "classncine_1_1_joy_connection_event" ],
      [ "JoyHatEvent", "classncine_1_1_joy_hat_event.html", "classncine_1_1_joy_hat_event" ],
      [ "JoyMappedAxisEvent", "classncine_1_1_joy_mapped_axis_event.html", "classncine_1_1_joy_mapped_axis_event" ],
      [ "JoyMappedButtonEvent", "classncine_1_1_joy_mapped_button_event.html", "classncine_1_1_joy_mapped_button_event" ],
      [ "JoyMappedState", "classncine_1_1_joy_mapped_state.html", "classncine_1_1_joy_mapped_state" ],
      [ "JoystickState", "classncine_1_1_joystick_state.html", "classncine_1_1_joystick_state" ],
      [ "KeyboardEvent", "classncine_1_1_keyboard_event.html", "classncine_1_1_keyboard_event" ],
      [ "KeyboardState", "classncine_1_1_keyboard_state.html", "classncine_1_1_keyboard_state" ],
      [ "LuaColorfUtils", "classncine_1_1_lua_colorf_utils.html", null ],
      [ "LuaColorUtils", "classncine_1_1_lua_color_utils.html", null ],
      [ "LuaIAppEventHandler", "classncine_1_1_lua_i_app_event_handler.html", null ],
      [ "LuaIInputEventHandler", "classncine_1_1_lua_i_input_event_handler.html", null ],
      [ "LuaRectUtils", "classncine_1_1_lua_rect_utils.html", null ],
      [ "LuaStateManager", "classncine_1_1_lua_state_manager.html", "classncine_1_1_lua_state_manager" ],
      [ "LuaUntrackedUserData", "classncine_1_1_lua_untracked_user_data.html", null ],
      [ "LuaVector2Utils", "classncine_1_1_lua_vector2_utils.html", null ],
      [ "LuaVector3Utils", "classncine_1_1_lua_vector3_utils.html", null ],
      [ "LuaVector4Utils", "classncine_1_1_lua_vector4_utils.html", null ],
      [ "Matrix4x4", "classncine_1_1_matrix4x4.html", null ],
      [ "MeshSprite", "classncine_1_1_mesh_sprite.html", "classncine_1_1_mesh_sprite" ],
      [ "MouseEvent", "classncine_1_1_mouse_event.html", "classncine_1_1_mouse_event" ],
      [ "MouseState", "classncine_1_1_mouse_state.html", "classncine_1_1_mouse_state" ],
      [ "NuklearContext", "classncine_1_1_nuklear_context.html", null ],
      [ "NullAudioDevice", "classncine_1_1_null_audio_device.html", "classncine_1_1_null_audio_device" ],
      [ "NullGfxCapabilities", "classncine_1_1_null_gfx_capabilities.html", "classncine_1_1_null_gfx_capabilities" ],
      [ "NullIndexer", "classncine_1_1_null_indexer.html", "classncine_1_1_null_indexer" ],
      [ "NullJobSystem", "classncine_1_1_null_job_system.html", "classncine_1_1_null_job_system" ],
      [ "NullLogger", "classncine_1_1_null_logger.html", "classncine_1_1_null_logger" ],
      [ "Object", "classncine_1_1_object.html", "classncine_1_1_object" ],
      [ "parallelForJobData", "structncine_1_1parallel_for_job_data.html", null ],
      [ "Particle", "classncine_1_1_particle.html", "classncine_1_1_particle" ],
      [ "ParticleAffector", "classncine_1_1_particle_affector.html", "classncine_1_1_particle_affector" ],
      [ "ParticleInitializer", "structncine_1_1_particle_initializer.html", "structncine_1_1_particle_initializer" ],
      [ "ParticleSystem", "classncine_1_1_particle_system.html", "classncine_1_1_particle_system" ],
      [ "PCApplication", "classncine_1_1_p_c_application.html", "classncine_1_1_p_c_application" ],
      [ "PositionAffector", "classncine_1_1_position_affector.html", "classncine_1_1_position_affector" ],
      [ "Qt5Widget", "classncine_1_1_qt5_widget.html", "classncine_1_1_qt5_widget" ],
      [ "Quaternion", "classncine_1_1_quaternion.html", null ],
      [ "Random", "classncine_1_1_random.html", "classncine_1_1_random" ],
      [ "Rect", "classncine_1_1_rect.html", "classncine_1_1_rect" ],
      [ "RectAnimation", "classncine_1_1_rect_animation.html", "classncine_1_1_rect_animation" ],
      [ "RenderDocCapture", "classncine_1_1_render_doc_capture.html", null ],
      [ "RotationAffector", "classncine_1_1_rotation_affector.html", "classncine_1_1_rotation_affector" ],
      [ "SceneNode", "classncine_1_1_scene_node.html", "classncine_1_1_scene_node" ],
      [ "ScopedJobHandle", "classncine_1_1_scoped_job_handle.html", "classncine_1_1_scoped_job_handle" ],
      [ "ScrollEvent", "classncine_1_1_scroll_event.html", "classncine_1_1_scroll_event" ],
      [ "ServiceLocator", "classncine_1_1_service_locator.html", "classncine_1_1_service_locator" ],
      [ "Shader", "classncine_1_1_shader.html", "classncine_1_1_shader" ],
      [ "ShaderState", "classncine_1_1_shader_state.html", "classncine_1_1_shader_state" ],
      [ "SizeAffector", "classncine_1_1_size_affector.html", "classncine_1_1_size_affector" ],
      [ "Sprite", "classncine_1_1_sprite.html", "classncine_1_1_sprite" ],
      [ "StorageAlign", "structncine_1_1_storage_align.html", null ],
      [ "StorageAlign< float >", "structncine_1_1_storage_align_3_01float_01_4.html", null ],
      [ "TextInputEvent", "classncine_1_1_text_input_event.html", "classncine_1_1_text_input_event" ],
      [ "TextNode", "classncine_1_1_text_node.html", "classncine_1_1_text_node" ],
      [ "Texture", "classncine_1_1_texture.html", "classncine_1_1_texture" ],
      [ "TextureLoaderImage", "classncine_1_1_texture_loader_image.html", null ],
      [ "Timer", "classncine_1_1_timer.html", "classncine_1_1_timer" ],
      [ "TimeStamp", "classncine_1_1_time_stamp.html", "classncine_1_1_time_stamp" ],
      [ "TouchEvent", "classncine_1_1_touch_event.html", "classncine_1_1_touch_event" ],
      [ "Vector2", "classncine_1_1_vector2.html", null ],
      [ "Vector3", "classncine_1_1_vector3.html", null ],
      [ "Vector4", "classncine_1_1_vector4.html", null ],
      [ "VelocityAffector", "classncine_1_1_velocity_affector.html", "classncine_1_1_velocity_affector" ],
      [ "Viewport", "classncine_1_1_viewport.html", "classncine_1_1_viewport" ]
    ] ],
    [ "nctl", null, [
      [ "deprecated", null, [
        [ "FNV1aHashFunc", "classnctl_1_1deprecated_1_1_f_n_v1a_hash_func.html", null ],
        [ "JenkinsHashFunc", "classnctl_1_1deprecated_1_1_jenkins_hash_func.html", null ],
        [ "SaxHashFunc", "classnctl_1_1deprecated_1_1_sax_hash_func.html", null ]
      ] ],
      [ "detail", null, [
        [ "allocHelpers", "structnctl_1_1detail_1_1alloc_helpers.html", null ],
        [ "allocHelpers< true >", "structnctl_1_1detail_1_1alloc_helpers_3_01true_01_4.html", null ],
        [ "constructHelpers", "structnctl_1_1detail_1_1construct_helpers.html", null ],
        [ "constructHelpersImpl", "structnctl_1_1detail_1_1construct_helpers_impl.html", null ],
        [ "constructHelpersImpl< T, CopyableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_3_01_t_00_01_copyable_tag_01_4.html", null ],
        [ "constructHelpersImpl< T, MovableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_3_01_t_00_01_movable_tag_01_4.html", null ],
        [ "constructHelpersImpl< T, MoveOnlyTag >", "structnctl_1_1detail_1_1construct_helpers_impl_3_01_t_00_01_move_only_tag_01_4.html", null ],
        [ "constructHelpersImpl< T, NonMovableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_3_01_t_00_01_non_movable_tag_01_4.html", null ],
        [ "constructHelpersImpl< T, TrivialTag >", "structnctl_1_1detail_1_1construct_helpers_impl_3_01_t_00_01_trivial_tag_01_4.html", null ],
        [ "constructHelpersImplSingle", "structnctl_1_1detail_1_1construct_helpers_impl_single.html", null ],
        [ "constructHelpersImplSingle< T, CopyableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_3_01_t_00_01_copyable_tag_01_4.html", null ],
        [ "constructHelpersImplSingle< T, MovableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_3_01_t_00_01_movable_tag_01_4.html", null ],
        [ "constructHelpersImplSingle< T, MoveOnlyTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_3_01_t_00_01_move_only_tag_01_4.html", null ],
        [ "constructHelpersImplSingle< T, NonMovableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_3_01_t_00_01_non_movable_tag_01_4.html", null ],
        [ "constructHelpersImplSingle< T, TrivialTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_3_01_t_00_01_trivial_tag_01_4.html", null ],
        [ "constructHelpersImplSingleArray", "structnctl_1_1detail_1_1construct_helpers_impl_single_array.html", null ],
        [ "constructHelpersImplSingleArray< T, NonMovableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_array_3_01_t_00_01_non_movable_tag_01_4.html", null ],
        [ "constructHelpersImplSingleArray< T, TrivialTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_array_3_01_t_00_01_trivial_tag_01_4.html", null ],
        [ "CopyableTag", "structnctl_1_1detail_1_1_copyable_tag.html", null ],
        [ "copyHelpersImpl", "structnctl_1_1detail_1_1copy_helpers_impl.html", null ],
        [ "copyHelpersImpl< T, CopyableTag >", "structnctl_1_1detail_1_1copy_helpers_impl_3_01_t_00_01_copyable_tag_01_4.html", null ],
        [ "copyHelpersImpl< T, MovableTag >", "structnctl_1_1detail_1_1copy_helpers_impl_3_01_t_00_01_movable_tag_01_4.html", null ],
        [ "copyHelpersImpl< T, MoveOnlyTag >", "structnctl_1_1detail_1_1copy_helpers_impl_3_01_t_00_01_move_only_tag_01_4.html", null ],
        [ "copyHelpersImpl< T, NonMovableTag >", "structnctl_1_1detail_1_1copy_helpers_impl_3_01_t_00_01_non_movable_tag_01_4.html", null ],
        [ "copyHelpersImpl< T, TrivialTag >", "structnctl_1_1detail_1_1copy_helpers_impl_3_01_t_00_01_trivial_tag_01_4.html", null ],
        [ "destructHelpers", "structnctl_1_1detail_1_1destruct_helpers.html", null ],
        [ "destructHelpers< true >", "structnctl_1_1detail_1_1destruct_helpers_3_01true_01_4.html", null ],
        [ "isTrivial", "structnctl_1_1detail_1_1is_trivial.html", null ],
        [ "KeyBytes", "structnctl_1_1detail_1_1_key_bytes.html", null ],
        [ "KeyBytes< const char * >", "structnctl_1_1detail_1_1_key_bytes_3_01const_01char_01_5_01_4.html", null ],
        [ "KeyBytes< String >", "structnctl_1_1detail_1_1_key_bytes_3_01_string_01_4.html", null ],
        [ "MovableTag", "structnctl_1_1detail_1_1_movable_tag.html", null ],
        [ "MoveOnlyTag", "structnctl_1_1detail_1_1_move_only_tag.html", null ],
        [ "NonMovableTag", "structnctl_1_1detail_1_1_non_movable_tag.html", null ],
        [ "ObjectPolicyTag", "structnctl_1_1detail_1_1_object_policy_tag.html", null ],
        [ "PairImpl", "structnctl_1_1detail_1_1_pair_impl.html", null ],
        [ "PairImpl< T1, T2, true >", "structnctl_1_1detail_1_1_pair_impl_3_01_t1_00_01_t2_00_01true_01_4.html", null ],
        [ "TrivialTag", "structnctl_1_1detail_1_1_trivial_tag.html", null ],
        [ "typeIdentity", "structnctl_1_1detail_1_1type_identity.html", null ],
        [ "voidType", "structnctl_1_1detail_1_1void_type.html", null ]
      ] ],
      [ "addLValueReference", "structnctl_1_1add_l_value_reference.html", null ],
      [ "addRValueReference", "structnctl_1_1add_r_value_reference.html", null ],
      [ "AllocManager", "classnctl_1_1_alloc_manager.html", null ],
      [ "AllocManagerInitializer", "classnctl_1_1_alloc_manager_initializer.html", null ],
      [ "Array", "classnctl_1_1_array.html", "classnctl_1_1_array" ],
      [ "ArrayIterator", "classnctl_1_1_array_iterator.html", "classnctl_1_1_array_iterator" ],
      [ "Atomic32", "classnctl_1_1_atomic32.html", null ],
      [ "Atomic64", "classnctl_1_1_atomic64.html", null ],
      [ "AtomicU32", "classnctl_1_1_atomic_u32.html", null ],
      [ "AtomicU64", "classnctl_1_1_atomic_u64.html", null ],
      [ "BaseListNode", "classnctl_1_1_base_list_node.html", "classnctl_1_1_base_list_node" ],
      [ "BidirectionalIteratorTag", "structnctl_1_1_bidirectional_iterator_tag.html", null ],
      [ "BitSet", "classnctl_1_1_bit_set.html", "classnctl_1_1_bit_set" ],
      [ "conditional", "structnctl_1_1conditional.html", null ],
      [ "conditional< false, T, F >", "structnctl_1_1conditional_3_01false_00_01_t_00_01_f_01_4.html", null ],
      [ "Decay", "structnctl_1_1_decay.html", null ],
      [ "decayArray", "structnctl_1_1decay_array.html", null ],
      [ "decayArray< T(Args...)>", "structnctl_1_1decay_array_3_01_t_07_args_8_8_8_08_4.html", null ],
      [ "decayArray< T[]>", "structnctl_1_1decay_array_3_01_t_0f_0e_4.html", null ],
      [ "decayArray< T[N]>", "structnctl_1_1decay_array_3_01_t_0f_n_0e_4.html", null ],
      [ "DefaultDelete", "classnctl_1_1_default_delete.html", null ],
      [ "DefaultDelete< T[]>", "classnctl_1_1_default_delete_3_01_t_0f_0e_4.html", null ],
      [ "enableIf", "structnctl_1_1enable_if.html", null ],
      [ "enableIf< true, T >", "structnctl_1_1enable_if_3_01true_00_01_t_01_4.html", null ],
      [ "FastHashFunc", "classnctl_1_1_fast_hash_func.html", null ],
      [ "FixedHashFunc", "classnctl_1_1_fixed_hash_func.html", null ],
      [ "Fold64To32Hash", "classnctl_1_1_fold64_to32_hash.html", null ],
      [ "ForwardIteratorTag", "structnctl_1_1_forward_iterator_tag.html", null ],
      [ "FreeListAllocator", "classnctl_1_1_free_list_allocator.html", "classnctl_1_1_free_list_allocator" ],
      [ "HashMap", "classnctl_1_1_hash_map.html", "classnctl_1_1_hash_map" ],
      [ "HashMapHelperTraits", "structnctl_1_1_hash_map_helper_traits.html", null ],
      [ "HashMapHelperTraits< K, T, HashFunc, false >", "structnctl_1_1_hash_map_helper_traits_3_01_k_00_01_t_00_01_hash_func_00_01false_01_4.html", null ],
      [ "HashMapHelperTraits< K, T, HashFunc, true >", "structnctl_1_1_hash_map_helper_traits_3_01_k_00_01_t_00_01_hash_func_00_01true_01_4.html", null ],
      [ "HashMapIterator", "classnctl_1_1_hash_map_iterator.html", "classnctl_1_1_hash_map_iterator" ],
      [ "HashMapList", "classnctl_1_1_hash_map_list.html", "classnctl_1_1_hash_map_list" ],
      [ "HashMapListHelperTraits", "structnctl_1_1_hash_map_list_helper_traits.html", null ],
      [ "HashMapListHelperTraits< K, T, HashFunc, false >", "structnctl_1_1_hash_map_list_helper_traits_3_01_k_00_01_t_00_01_hash_func_00_01false_01_4.html", null ],
      [ "HashMapListHelperTraits< K, T, HashFunc, true >", "structnctl_1_1_hash_map_list_helper_traits_3_01_k_00_01_t_00_01_hash_func_00_01true_01_4.html", null ],
      [ "HashMapListIterator", "classnctl_1_1_hash_map_list_iterator.html", "classnctl_1_1_hash_map_list_iterator" ],
      [ "HashSet", "classnctl_1_1_hash_set.html", "classnctl_1_1_hash_set" ],
      [ "HashSetHelperTraits", "structnctl_1_1_hash_set_helper_traits.html", null ],
      [ "HashSetIterator", "classnctl_1_1_hash_set_iterator.html", "classnctl_1_1_hash_set_iterator" ],
      [ "HashSetList", "classnctl_1_1_hash_set_list.html", "classnctl_1_1_hash_set_list" ],
      [ "HashSetListHelperTraits", "structnctl_1_1_hash_set_list_helper_traits.html", null ],
      [ "HashSetListIterator", "classnctl_1_1_hash_set_list_iterator.html", "classnctl_1_1_hash_set_list_iterator" ],
      [ "IAllocator", "classnctl_1_1_i_allocator.html", "classnctl_1_1_i_allocator" ],
      [ "IdentityHashFunc", "classnctl_1_1_identity_hash_func.html", null ],
      [ "integralConstant", "structnctl_1_1integral_constant.html", null ],
      [ "isClass", "structnctl_1_1is_class.html", null ],
      [ "isClass< T, typename detail::voidType< int T::* >::type >", "structnctl_1_1is_class_3_01_t_00_01typename_01detail_1_1void_type_3_01int_01_t_1_1_5_01_4_1_1type_01_4.html", null ],
      [ "isConvertible", "structnctl_1_1is_convertible.html", null ],
      [ "isCopyConstructible", "structnctl_1_1is_copy_constructible.html", null ],
      [ "isDestructible", "structnctl_1_1is_destructible.html", null ],
      [ "isDestructible< T, decltype(declVal< T & >().~T())>", "structnctl_1_1is_destructible_3_01_t_00_01decltype_07decl_val_3_01_t_01_6_01_4_07_08_8_0i_t_07_08_08_4.html", null ],
      [ "isEmpty", "structnctl_1_1is_empty.html", null ],
      [ "IsEqualTo", "classnctl_1_1_is_equal_to.html", null ],
      [ "IsGreaterThan", "classnctl_1_1_is_greater_than.html", null ],
      [ "isIntegral", "structnctl_1_1is_integral.html", null ],
      [ "isIntegral< bool >", "structnctl_1_1is_integral_3_01bool_01_4.html", null ],
      [ "isIntegral< char >", "structnctl_1_1is_integral_3_01char_01_4.html", null ],
      [ "isIntegral< int >", "structnctl_1_1is_integral_3_01int_01_4.html", null ],
      [ "isIntegral< long >", "structnctl_1_1is_integral_3_01long_01_4.html", null ],
      [ "isIntegral< long long >", "structnctl_1_1is_integral_3_01long_01long_01_4.html", null ],
      [ "isIntegral< short int >", "structnctl_1_1is_integral_3_01short_01int_01_4.html", null ],
      [ "isIntegral< unsigned char >", "structnctl_1_1is_integral_3_01unsigned_01char_01_4.html", null ],
      [ "isIntegral< unsigned int >", "structnctl_1_1is_integral_3_01unsigned_01int_01_4.html", null ],
      [ "isIntegral< unsigned long >", "structnctl_1_1is_integral_3_01unsigned_01long_01_4.html", null ],
      [ "isIntegral< unsigned long long >", "structnctl_1_1is_integral_3_01unsigned_01long_01long_01_4.html", null ],
      [ "isIntegral< unsigned short int >", "structnctl_1_1is_integral_3_01unsigned_01short_01int_01_4.html", null ],
      [ "IsLessThan", "classnctl_1_1_is_less_than.html", null ],
      [ "isLValueReference", "structnctl_1_1is_l_value_reference.html", null ],
      [ "isLValueReference< T & >", "structnctl_1_1is_l_value_reference_3_01_t_01_6_01_4.html", null ],
      [ "isMoveConstructible", "structnctl_1_1is_move_constructible.html", null ],
      [ "IsNotEqualTo", "classnctl_1_1_is_not_equal_to.html", null ],
      [ "IsNotGreaterThan", "classnctl_1_1_is_not_greater_than.html", null ],
      [ "isNoThrowConstructible", "structnctl_1_1is_no_throw_constructible.html", null ],
      [ "IsNotLessThan", "classnctl_1_1_is_not_less_than.html", null ],
      [ "isSame", "structnctl_1_1is_same.html", null ],
      [ "isSame< T, T >", "structnctl_1_1is_same_3_01_t_00_01_t_01_4.html", null ],
      [ "isTriviallyConstructible", "structnctl_1_1is_trivially_constructible.html", null ],
      [ "isTriviallyCopyable", "structnctl_1_1is_trivially_copyable.html", null ],
      [ "isTriviallyDestructible", "structnctl_1_1is_trivially_destructible.html", null ],
      [ "IteratorTraits", "structnctl_1_1_iterator_traits.html", null ],
      [ "IteratorTraits< ArrayIterator< T, false > >", "structnctl_1_1_iterator_traits_3_01_array_iterator_3_01_t_00_01false_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_array_iterator_3_01_t_00_01false_01_4_01_4" ],
      [ "IteratorTraits< ArrayIterator< T, true > >", "structnctl_1_1_iterator_traits_3_01_array_iterator_3_01_t_00_01true_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_array_iterator_3_01_t_00_01true_01_4_01_4" ],
      [ "IteratorTraits< const T * >", "structnctl_1_1_iterator_traits_3_01const_01_t_01_5_01_4.html", null ],
      [ "IteratorTraits< HashMapIterator< K, T, HashFunc, false > >", "structnctl_1_1_iterator_traits_3_01_hash_map_iterator_3_01_k_00_01_t_00_01_hash_func_00_01false_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_hash_map_iterator_3_01_k_00_01_t_00_01_hash_func_00_01false_01_4_01_4" ],
      [ "IteratorTraits< HashMapIterator< K, T, HashFunc, true > >", "structnctl_1_1_iterator_traits_3_01_hash_map_iterator_3_01_k_00_01_t_00_01_hash_func_00_01true_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_hash_map_iterator_3_01_k_00_01_t_00_01_hash_func_00_01true_01_4_01_4" ],
      [ "IteratorTraits< HashMapListIterator< K, T, HashFunc, false > >", "structnctl_1_1_iterator_traits_3_01_hash_map_list_iterator_3_01_k_00_01_t_00_01_hash_func_00_01false_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_hash_map_list_iterator_3_01_k_00_01_t_00_01_hash_func_00_01false_01_4_01_4" ],
      [ "IteratorTraits< HashMapListIterator< K, T, HashFunc, true > >", "structnctl_1_1_iterator_traits_3_01_hash_map_list_iterator_3_01_k_00_01_t_00_01_hash_func_00_01true_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_hash_map_list_iterator_3_01_k_00_01_t_00_01_hash_func_00_01true_01_4_01_4" ],
      [ "IteratorTraits< HashSetIterator< K, HashFunc > >", "structnctl_1_1_iterator_traits_3_01_hash_set_iterator_3_01_k_00_01_hash_func_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_hash_set_iterator_3_01_k_00_01_hash_func_01_4_01_4" ],
      [ "IteratorTraits< HashSetListIterator< K, HashFunc > >", "structnctl_1_1_iterator_traits_3_01_hash_set_list_iterator_3_01_k_00_01_hash_func_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_hash_set_list_iterator_3_01_k_00_01_hash_func_01_4_01_4" ],
      [ "IteratorTraits< ListIterator< T, false > >", "structnctl_1_1_iterator_traits_3_01_list_iterator_3_01_t_00_01false_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_list_iterator_3_01_t_00_01false_01_4_01_4" ],
      [ "IteratorTraits< ListIterator< T, true > >", "structnctl_1_1_iterator_traits_3_01_list_iterator_3_01_t_00_01true_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_list_iterator_3_01_t_00_01true_01_4_01_4" ],
      [ "IteratorTraits< ReverseIterator< Iterator > >", "structnctl_1_1_iterator_traits_3_01_reverse_iterator_3_01_iterator_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_reverse_iterator_3_01_iterator_01_4_01_4" ],
      [ "IteratorTraits< SparseSetIterator< T > >", "structnctl_1_1_iterator_traits_3_01_sparse_set_iterator_3_01_t_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_sparse_set_iterator_3_01_t_01_4_01_4" ],
      [ "IteratorTraits< StaticHashMapIterator< K, T, HashFunc, Capacity, false > >", "structnctl_1_1_iterator_traits_3_01_static_hash_map_iterator_3_01_k_00_01_t_00_01_hash_func_00_01_capacity_00_01false_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_static_hash_map_iterator_3_01_k_00_01_t_00_01_hash_func_00_01_capacity_00_01false_01_4_01_4" ],
      [ "IteratorTraits< StaticHashMapIterator< K, T, HashFunc, Capacity, true > >", "structnctl_1_1_iterator_traits_3_01_static_hash_map_iterator_3_01_k_00_01_t_00_01_hash_func_00_01_capacity_00_01true_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_static_hash_map_iterator_3_01_k_00_01_t_00_01_hash_func_00_01_capacity_00_01true_01_4_01_4" ],
      [ "IteratorTraits< StaticHashSetIterator< K, HashFunc, Capacity > >", "structnctl_1_1_iterator_traits_3_01_static_hash_set_iterator_3_01_k_00_01_hash_func_00_01_capacity_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_static_hash_set_iterator_3_01_k_00_01_hash_func_00_01_capacity_01_4_01_4" ],
      [ "IteratorTraits< StringIterator< false > >", "structnctl_1_1_iterator_traits_3_01_string_iterator_3_01false_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_string_iterator_3_01false_01_4_01_4" ],
      [ "IteratorTraits< StringIterator< true > >", "structnctl_1_1_iterator_traits_3_01_string_iterator_3_01true_01_4_01_4.html", "structnctl_1_1_iterator_traits_3_01_string_iterator_3_01true_01_4_01_4" ],
      [ "IteratorTraits< T * >", "structnctl_1_1_iterator_traits_3_01_t_01_5_01_4.html", null ],
      [ "LinearAllocator", "classnctl_1_1_linear_allocator.html", "classnctl_1_1_linear_allocator" ],
      [ "List", "classnctl_1_1_list.html", "classnctl_1_1_list" ],
      [ "ListIterator", "classnctl_1_1_list_iterator.html", "classnctl_1_1_list_iterator" ],
      [ "ListNode", "classnctl_1_1_list_node.html", "classnctl_1_1_list_node" ],
      [ "MakeUniqueReturn", "structnctl_1_1_make_unique_return.html", null ],
      [ "MakeUniqueReturn< T[], Deleter >", "structnctl_1_1_make_unique_return_3_01_t_0f_0e_00_01_deleter_01_4.html", null ],
      [ "MakeUniqueReturn< T[size], Deleter >", "structnctl_1_1_make_unique_return_3_01_t_0fsize_0e_00_01_deleter_01_4.html", "structnctl_1_1_make_unique_return_3_01_t_0fsize_0e_00_01_deleter_01_4" ],
      [ "MallocAllocator", "classnctl_1_1_malloc_allocator.html", null ],
      [ "ModuloHashFunc", "classnctl_1_1_modulo_hash_func.html", null ],
      [ "Mul64To32Hash", "classnctl_1_1_mul64_to32_hash.html", null ],
      [ "NullOptTag", "structnctl_1_1_null_opt_tag.html", null ],
      [ "Optional", "classnctl_1_1_optional.html", null ],
      [ "Pair", "structnctl_1_1_pair.html", null ],
      [ "PoolAllocator", "classnctl_1_1_pool_allocator.html", null ],
      [ "ProxyAllocator", "classnctl_1_1_proxy_allocator.html", null ],
      [ "RandomAccessIteratorTag", "structnctl_1_1_random_access_iterator_tag.html", null ],
      [ "removeConst", "structnctl_1_1remove_const.html", null ],
      [ "removeConst< const T >", "structnctl_1_1remove_const_3_01const_01_t_01_4.html", null ],
      [ "removeCv", "structnctl_1_1remove_cv.html", null ],
      [ "removeExtent", "structnctl_1_1remove_extent.html", null ],
      [ "removeExtent< T[]>", "structnctl_1_1remove_extent_3_01_t_0f_0e_4.html", null ],
      [ "removeExtent< T[N]>", "structnctl_1_1remove_extent_3_01_t_0f_n_0e_4.html", null ],
      [ "removeReference", "structnctl_1_1remove_reference.html", null ],
      [ "removeReference< T & >", "structnctl_1_1remove_reference_3_01_t_01_6_01_4.html", null ],
      [ "removeReference< T && >", "structnctl_1_1remove_reference_3_01_t_01_6_6_01_4.html", null ],
      [ "removeVolatile", "structnctl_1_1remove_volatile.html", null ],
      [ "removeVolatile< volatile T >", "structnctl_1_1remove_volatile_3_01volatile_01_t_01_4.html", null ],
      [ "ReverseIterator", "classnctl_1_1_reverse_iterator.html", "classnctl_1_1_reverse_iterator" ],
      [ "ReversionWrapper", "structnctl_1_1_reversion_wrapper.html", null ],
      [ "SharedPtr", "classnctl_1_1_shared_ptr.html", null ],
      [ "Span", "classnctl_1_1_span.html", "classnctl_1_1_span" ],
      [ "SparseSet", "classnctl_1_1_sparse_set.html", "classnctl_1_1_sparse_set" ],
      [ "SparseSetIterator", "classnctl_1_1_sparse_set_iterator.html", "classnctl_1_1_sparse_set_iterator" ],
      [ "StackAllocator", "classnctl_1_1_stack_allocator.html", null ],
      [ "StaticArray", "classnctl_1_1_static_array.html", "classnctl_1_1_static_array" ],
      [ "StaticHashMap", "classnctl_1_1_static_hash_map.html", "classnctl_1_1_static_hash_map" ],
      [ "StaticHashMapHelperTraits", "structnctl_1_1_static_hash_map_helper_traits.html", null ],
      [ "StaticHashMapHelperTraits< K, T, HashFunc, Capacity, false >", "structnctl_1_1_static_hash_map_helper_traits_3_01_k_00_01_t_00_01_hash_func_00_01_capacity_00_01false_01_4.html", null ],
      [ "StaticHashMapHelperTraits< K, T, HashFunc, Capacity, true >", "structnctl_1_1_static_hash_map_helper_traits_3_01_k_00_01_t_00_01_hash_func_00_01_capacity_00_01true_01_4.html", null ],
      [ "StaticHashMapIterator", "classnctl_1_1_static_hash_map_iterator.html", "classnctl_1_1_static_hash_map_iterator" ],
      [ "StaticHashSet", "classnctl_1_1_static_hash_set.html", "classnctl_1_1_static_hash_set" ],
      [ "StaticHashSetHelperTraits", "structnctl_1_1_static_hash_set_helper_traits.html", null ],
      [ "StaticHashSetIterator", "classnctl_1_1_static_hash_set_iterator.html", "classnctl_1_1_static_hash_set_iterator" ],
      [ "StaticString", "classnctl_1_1_static_string.html", "classnctl_1_1_static_string" ],
      [ "String", "classnctl_1_1_string.html", "classnctl_1_1_string" ],
      [ "StringIterator", "classnctl_1_1_string_iterator.html", "classnctl_1_1_string_iterator" ],
      [ "StringView", "classnctl_1_1_string_view.html", "classnctl_1_1_string_view" ],
      [ "UniquePtr", "classnctl_1_1_unique_ptr.html", null ],
      [ "UniquePtr< T[], Deleter >", "classnctl_1_1_unique_ptr_3_01_t_0f_0e_00_01_deleter_01_4.html", null ]
    ] ],
    [ "tracy", null, [
      [ "GpuCtxScope", "classtracy_1_1_gpu_ctx_scope.html", null ]
    ] ]
];