var hierarchy =
[
    [ "ncine::IAudioDevice::ALExtensions", "structncine_1_1_i_audio_device_1_1_a_l_extensions.html", null ],
    [ "nctl::detail::allocHelpers< value >", "structnctl_1_1detail_1_1alloc_helpers.html", null ],
    [ "nctl::detail::allocHelpers< true >", "structnctl_1_1detail_1_1alloc_helpers_3_01true_01_4.html", null ],
    [ "nctl::AllocManager", "classnctl_1_1_alloc_manager.html", null ],
    [ "nctl::AllocManagerInitializer", "classnctl_1_1_alloc_manager_initializer.html", null ],
    [ "ncine::AppConfiguration", "classncine_1_1_app_configuration.html", null ],
    [ "ncine::Application", "classncine_1_1_application.html", [
      [ "ncine::AndroidApplication", "classncine_1_1_android_application.html", null ],
      [ "ncine::PCApplication", "classncine_1_1_p_c_application.html", null ]
    ] ],
    [ "nctl::Array< T >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< float >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< HashBucket >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< ncine::ColorAffector::ColorStep >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< ncine::LuaStateManager::StateToManager >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< ncine::Particle * >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< ncine::PositionAffector::PositionStep >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< ncine::RectAnimation >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< ncine::RotationAffector::RotationStep >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< ncine::SceneNode * >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< ncine::SizeAffector::SizeStep >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< ncine::VelocityAffector::VelocityStep >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< ncine::Viewport * >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< nctl::String >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< nctl::UniquePtr< ncine::Particle > >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< nctl::UniquePtr< ncine::ParticleAffector > >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< Rect< int > >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< unsigned short >", "classnctl_1_1_array.html", null ],
    [ "nctl::Array< Vertex >", "classnctl_1_1_array.html", null ],
    [ "nctl::ArrayIterator< T, IsConst >", "classnctl_1_1_array_iterator.html", null ],
    [ "nctl::Atomic32", "classnctl_1_1_atomic32.html", null ],
    [ "nctl::Atomic64", "classnctl_1_1_atomic64.html", null ],
    [ "nctl::AtomicU32", "classnctl_1_1_atomic_u32.html", null ],
    [ "nctl::AtomicU64", "classnctl_1_1_atomic_u64.html", null ],
    [ "ncine::IAudioDevice::Attributes", "structncine_1_1_i_audio_device_1_1_attributes.html", null ],
    [ "ncine::AppConfiguration::Audio", "structncine_1_1_app_configuration_1_1_audio.html", null ],
    [ "ncine::AudioEffect", "classncine_1_1_audio_effect.html", null ],
    [ "ncine::AudioEffectProperties", "classncine_1_1_audio_effect_properties.html", null ],
    [ "ncine::AudioEffectSlot", "classncine_1_1_audio_effect_slot.html", null ],
    [ "ncine::AudioFilter", "classncine_1_1_audio_filter.html", null ],
    [ "ncine::AudioStream", "classncine_1_1_audio_stream.html", null ],
    [ "ncine::AudioEffectProperties::AutoWahProperties", "structncine_1_1_audio_effect_properties_1_1_auto_wah_properties.html", null ],
    [ "nctl::BaseListNode", "classnctl_1_1_base_list_node.html", [
      [ "nctl::ListNode< T >", "classnctl_1_1_list_node.html", null ]
    ] ],
    [ "nctl::BitSet< T >", "classnctl_1_1_bit_set.html", null ],
    [ "nctl::BitSet< uint8_t >", "classnctl_1_1_bit_set.html", null ],
    [ "nctl::FreeListAllocator::Block", "structnctl_1_1_free_list_allocator_1_1_block.html", null ],
    [ "ncine::Camera", "classncine_1_1_camera.html", null ],
    [ "ncine::AudioEffectProperties::ChorusProperties", "structncine_1_1_audio_effect_properties_1_1_chorus_properties.html", null ],
    [ "ncine::Color", "classncine_1_1_color.html", null ],
    [ "ncine::Colorf", "classncine_1_1_colorf.html", null ],
    [ "ncine::ColorHdr", "classncine_1_1_color_hdr.html", null ],
    [ "ncine::ColorAffector::ColorStep", "structncine_1_1_color_affector_1_1_color_step.html", null ],
    [ "ncine::AudioEffectProperties::CompressorProperties", "structncine_1_1_audio_effect_properties_1_1_compressor_properties.html", null ],
    [ "nctl::conditional< B, T, F >", "structnctl_1_1conditional.html", null ],
    [ "nctl::conditional< false, T, F >", "structnctl_1_1conditional_3_01false_00_01_t_00_01_f_01_4.html", null ],
    [ "nctl::detail::constructHelpers< T >", "structnctl_1_1detail_1_1construct_helpers.html", null ],
    [ "nctl::detail::constructHelpersImpl< T, Tag >", "structnctl_1_1detail_1_1construct_helpers_impl.html", null ],
    [ "nctl::detail::constructHelpersImpl< T, CopyableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_3_01_t_00_01_copyable_tag_01_4.html", null ],
    [ "nctl::detail::constructHelpersImpl< T, MovableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_3_01_t_00_01_movable_tag_01_4.html", null ],
    [ "nctl::detail::constructHelpersImpl< T, MoveOnlyTag >", "structnctl_1_1detail_1_1construct_helpers_impl_3_01_t_00_01_move_only_tag_01_4.html", null ],
    [ "nctl::detail::constructHelpersImpl< T, NonMovableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_3_01_t_00_01_non_movable_tag_01_4.html", null ],
    [ "nctl::detail::constructHelpersImpl< T, TrivialTag >", "structnctl_1_1detail_1_1construct_helpers_impl_3_01_t_00_01_trivial_tag_01_4.html", null ],
    [ "nctl::detail::constructHelpersImplSingle< T, Tag >", "structnctl_1_1detail_1_1construct_helpers_impl_single.html", null ],
    [ "nctl::detail::constructHelpersImplSingle< T, CopyableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_3_01_t_00_01_copyable_tag_01_4.html", null ],
    [ "nctl::detail::constructHelpersImplSingle< T, MovableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_3_01_t_00_01_movable_tag_01_4.html", null ],
    [ "nctl::detail::constructHelpersImplSingle< T, MoveOnlyTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_3_01_t_00_01_move_only_tag_01_4.html", null ],
    [ "nctl::detail::constructHelpersImplSingle< T, NonMovableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_3_01_t_00_01_non_movable_tag_01_4.html", null ],
    [ "nctl::detail::constructHelpersImplSingle< T, TrivialTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_3_01_t_00_01_trivial_tag_01_4.html", null ],
    [ "nctl::detail::constructHelpersImplSingleArray< T, Tag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_array.html", null ],
    [ "nctl::detail::constructHelpersImplSingleArray< T, NonMovableTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_array_3_01_t_00_01_non_movable_tag_01_4.html", null ],
    [ "nctl::detail::constructHelpersImplSingleArray< T, TrivialTag >", "structnctl_1_1detail_1_1construct_helpers_impl_single_array_3_01_t_00_01_trivial_tag_01_4.html", null ],
    [ "nctl::detail::CopyableTag", "structnctl_1_1detail_1_1_copyable_tag.html", null ],
    [ "nctl::detail::copyHelpersImpl< T, Tag >", "structnctl_1_1detail_1_1copy_helpers_impl.html", null ],
    [ "nctl::detail::copyHelpersImpl< T, CopyableTag >", "structnctl_1_1detail_1_1copy_helpers_impl_3_01_t_00_01_copyable_tag_01_4.html", null ],
    [ "nctl::detail::copyHelpersImpl< T, MovableTag >", "structnctl_1_1detail_1_1copy_helpers_impl_3_01_t_00_01_movable_tag_01_4.html", null ],
    [ "nctl::detail::copyHelpersImpl< T, MoveOnlyTag >", "structnctl_1_1detail_1_1copy_helpers_impl_3_01_t_00_01_move_only_tag_01_4.html", null ],
    [ "nctl::detail::copyHelpersImpl< T, NonMovableTag >", "structnctl_1_1detail_1_1copy_helpers_impl_3_01_t_00_01_non_movable_tag_01_4.html", null ],
    [ "nctl::detail::copyHelpersImpl< T, TrivialTag >", "structnctl_1_1detail_1_1copy_helpers_impl_3_01_t_00_01_trivial_tag_01_4.html", null ],
    [ "ncine::CountSplitter", "classncine_1_1_count_splitter.html", null ],
    [ "ncine::Crashpad", "classncine_1_1_crashpad.html", null ],
    [ "ncine::DataSizeSplitter", "classncine_1_1_data_size_splitter.html", null ],
    [ "ncine::LuaUtils::RunInfo::DebugInfo", "structncine_1_1_lua_utils_1_1_run_info_1_1_debug_info.html", null ],
    [ "nctl::Decay< T >", "structnctl_1_1_decay.html", null ],
    [ "nctl::decayArray< T >", "structnctl_1_1decay_array.html", null ],
    [ "nctl::decayArray< T(Args...)>", "structnctl_1_1decay_array_3_01_t_07_args_8_8_8_08_4.html", null ],
    [ "nctl::decayArray< T[]>", "structnctl_1_1decay_array_3_01_t_0f_0e_4.html", null ],
    [ "nctl::decayArray< T[N]>", "structnctl_1_1decay_array_3_01_t_0f_n_0e_4.html", null ],
    [ "nctl::DefaultDelete< T >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< char >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< crashpad::CrashpadClient >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< FontGlyph >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< FrameTimer >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< GLFramebufferObject >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< GLShaderProgram >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< GLTexture >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< IAudioReader >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< ncine::IAppEventHandler >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< ncine::IAudioDevice >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< ncine::IDebugOverlay >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< ncine::IGfxCapabilities >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< ncine::IGfxDevice >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< ncine::IIndexer >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< ncine::IInputManager >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< ncine::IJobSystem >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< ncine::ILogger >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< ncine::Particle >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< ncine::ParticleAffector >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< ncine::Texture >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< RenderCommand >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< RenderQueue >", "classnctl_1_1_default_delete.html", null ],
    [ "nctl::DefaultDelete< T[]>", "classnctl_1_1_default_delete_3_01_t_0f_0e_4.html", null ],
    [ "nctl::detail::destructHelpers< Trivial >", "structnctl_1_1detail_1_1destruct_helpers.html", null ],
    [ "nctl::detail::destructHelpers< true >", "structnctl_1_1detail_1_1destruct_helpers_3_01true_01_4.html", null ],
    [ "ncine::FileSystem::Directory", "classncine_1_1_file_system_1_1_directory.html", null ],
    [ "ncine::DisplayMode", "classncine_1_1_display_mode.html", null ],
    [ "ncine::IDebugOverlay::DisplaySettings", "structncine_1_1_i_debug_overlay_1_1_display_settings.html", null ],
    [ "ncine::AudioEffectProperties::DistortionProperties", "structncine_1_1_audio_effect_properties_1_1_distortion_properties.html", null ],
    [ "ncine::DropEvent", "classncine_1_1_drop_event.html", null ],
    [ "ncine::AudioEffectProperties::EaxReverbProperties", "structncine_1_1_audio_effect_properties_1_1_eax_reverb_properties.html", null ],
    [ "ncine::AudioEffectProperties::EchoProperties", "structncine_1_1_audio_effect_properties_1_1_echo_properties.html", null ],
    [ "ncine::EmscriptenLocalFile", "classncine_1_1_emscripten_local_file.html", null ],
    [ "nctl::enableIf< Condition, T >", "structnctl_1_1enable_if.html", null ],
    [ "nctl::enableIf< true, T >", "structnctl_1_1enable_if_3_01true_00_01_t_01_4.html", null ],
    [ "ncine::AudioEffectProperties::EqualizerProperties", "structncine_1_1_audio_effect_properties_1_1_equalizer_properties.html", null ],
    [ "nctl::FastHashFunc< K >", "classnctl_1_1_fast_hash_func.html", null ],
    [ "nctl::FastHashFunc< unsigned short int >", "classnctl_1_1_fast_hash_func.html", null ],
    [ "nctl::FastHashFunc< void * >", "classnctl_1_1_fast_hash_func.html", null ],
    [ "ncine::AppConfiguration::Features", "structncine_1_1_app_configuration_1_1_features.html", null ],
    [ "ncine::FileSystem::FileDate", "structncine_1_1_file_system_1_1_file_date.html", null ],
    [ "ncine::FileSystem", "classncine_1_1_file_system.html", null ],
    [ "nctl::FixedHashFunc< K >", "classnctl_1_1_fixed_hash_func.html", null ],
    [ "ncine::AudioEffectProperties::FlangerProperties", "structncine_1_1_audio_effect_properties_1_1_flanger_properties.html", null ],
    [ "nctl::deprecated::FNV1aHashFunc< K >", "classnctl_1_1deprecated_1_1_f_n_v1a_hash_func.html", null ],
    [ "nctl::Fold64To32Hash< K >", "classnctl_1_1_fold64_to32_hash.html", null ],
    [ "nctl::ForwardIteratorTag", "structnctl_1_1_forward_iterator_tag.html", [
      [ "nctl::BidirectionalIteratorTag", "structnctl_1_1_bidirectional_iterator_tag.html", [
        [ "nctl::RandomAccessIteratorTag", "structnctl_1_1_random_access_iterator_tag.html", null ]
      ] ]
    ] ],
    [ "ncine::AudioEffectProperties::FrequencyShifterProperties", "structncine_1_1_audio_effect_properties_1_1_frequency_shifter_properties.html", null ],
    [ "ncine::IGfxCapabilities::GLArrayIntValues", "structncine_1_1_i_gfx_capabilities_1_1_g_l_array_int_values.html", null ],
    [ "ncine::IGfxDevice::GLContextInfo", "structncine_1_1_i_gfx_device_1_1_g_l_context_info.html", null ],
    [ "ncine::IGfxCapabilities::GLExtensions", "structncine_1_1_i_gfx_capabilities_1_1_g_l_extensions.html", null ],
    [ "ncine::IGfxCapabilities::GlInfoStrings", "structncine_1_1_i_gfx_capabilities_1_1_gl_info_strings.html", null ],
    [ "ncine::IGfxCapabilities::GLIntValues", "structncine_1_1_i_gfx_capabilities_1_1_g_l_int_values.html", null ],
    [ "tracy::GpuCtxScope", "classtracy_1_1_gpu_ctx_scope.html", null ],
    [ "ncine::AppConfiguration::Graphics", "structncine_1_1_app_configuration_1_1_graphics.html", null ],
    [ "ncine::Application::GuiSettings", "structncine_1_1_application_1_1_gui_settings.html", null ],
    [ "ncine::Hash64", "classncine_1_1_hash64.html", null ],
    [ "nctl::HashMap< K, T, HashFunc >", "classnctl_1_1_hash_map.html", null ],
    [ "nctl::HashMap< unsigned short int, FontGlyph >", "classnctl_1_1_hash_map.html", null ],
    [ "nctl::HashMap< void *, LuaTypes::UserDataType >", "classnctl_1_1_hash_map.html", null ],
    [ "nctl::HashMapHelperTraits< K, T, HashFunc, IsConst >", "structnctl_1_1_hash_map_helper_traits.html", null ],
    [ "nctl::HashMapHelperTraits< K, T, HashFunc, false >", "structnctl_1_1_hash_map_helper_traits_3_01_k_00_01_t_00_01_hash_func_00_01false_01_4.html", null ],
    [ "nctl::HashMapHelperTraits< K, T, HashFunc, true >", "structnctl_1_1_hash_map_helper_traits_3_01_k_00_01_t_00_01_hash_func_00_01true_01_4.html", null ],
    [ "nctl::HashMapIterator< K, T, HashFunc, IsConst >", "classnctl_1_1_hash_map_iterator.html", null ],
    [ "nctl::HashMapList< K, T, HashFunc >", "classnctl_1_1_hash_map_list.html", null ],
    [ "nctl::HashMapListHelperTraits< K, T, HashFunc, IsConst >", "structnctl_1_1_hash_map_list_helper_traits.html", null ],
    [ "nctl::HashMapListHelperTraits< K, T, HashFunc, false >", "structnctl_1_1_hash_map_list_helper_traits_3_01_k_00_01_t_00_01_hash_func_00_01false_01_4.html", null ],
    [ "nctl::HashMapListHelperTraits< K, T, HashFunc, true >", "structnctl_1_1_hash_map_list_helper_traits_3_01_k_00_01_t_00_01_hash_func_00_01true_01_4.html", null ],
    [ "nctl::HashMapListIterator< K, T, HashFunc, IsConst >", "classnctl_1_1_hash_map_list_iterator.html", null ],
    [ "nctl::HashSet< K, HashFunc >", "classnctl_1_1_hash_set.html", null ],
    [ "nctl::HashSetHelperTraits< K, HashFunc >", "structnctl_1_1_hash_set_helper_traits.html", null ],
    [ "nctl::HashSetIterator< K, HashFunc >", "classnctl_1_1_hash_set_iterator.html", null ],
    [ "nctl::HashSetList< K, HashFunc >", "classnctl_1_1_hash_set_list.html", null ],
    [ "nctl::HashSetListHelperTraits< K, HashFunc >", "structnctl_1_1_hash_set_list_helper_traits.html", null ],
    [ "nctl::HashSetListIterator< K, HashFunc >", "classnctl_1_1_hash_set_list_iterator.html", null ],
    [ "ncine::HatState", "structncine_1_1_hat_state.html", null ],
    [ "nctl::IAllocator", "classnctl_1_1_i_allocator.html", [
      [ "nctl::FreeListAllocator", "classnctl_1_1_free_list_allocator.html", null ],
      [ "nctl::LinearAllocator", "classnctl_1_1_linear_allocator.html", null ],
      [ "nctl::MallocAllocator", "classnctl_1_1_malloc_allocator.html", null ],
      [ "nctl::PoolAllocator", "classnctl_1_1_pool_allocator.html", null ],
      [ "nctl::ProxyAllocator", "classnctl_1_1_proxy_allocator.html", null ],
      [ "nctl::StackAllocator", "classnctl_1_1_stack_allocator.html", null ]
    ] ],
    [ "ncine::IAppEventHandler", "classncine_1_1_i_app_event_handler.html", null ],
    [ "ncine::IAudioDevice", "classncine_1_1_i_audio_device.html", [
      [ "ncine::NullAudioDevice", "classncine_1_1_null_audio_device.html", null ]
    ] ],
    [ "ncine::IDebugOverlay", "classncine_1_1_i_debug_overlay.html", null ],
    [ "nctl::IdentityHashFunc< K >", "classnctl_1_1_identity_hash_func.html", null ],
    [ "ncine::IFile", "classncine_1_1_i_file.html", [
      [ "ncine::AssetFile", "classncine_1_1_asset_file.html", null ]
    ] ],
    [ "ncine::IFrameTimer", "classncine_1_1_i_frame_timer.html", null ],
    [ "ncine::IGfxCapabilities", "classncine_1_1_i_gfx_capabilities.html", [
      [ "ncine::NullGfxCapabilities", "classncine_1_1_null_gfx_capabilities.html", null ]
    ] ],
    [ "ncine::IGfxDevice", "classncine_1_1_i_gfx_device.html", null ],
    [ "ncine::IImageSaver", "classncine_1_1_i_image_saver.html", [
      [ "ncine::ImageSaverPng", "classncine_1_1_image_saver_png.html", null ],
      [ "ncine::ImageSaverWebP", "classncine_1_1_image_saver_web_p.html", null ]
    ] ],
    [ "ncine::IIndexer", "classncine_1_1_i_indexer.html", [
      [ "ncine::NullIndexer", "classncine_1_1_null_indexer.html", null ]
    ] ],
    [ "ncine::IInputEventHandler", "classncine_1_1_i_input_event_handler.html", null ],
    [ "ncine::IInputManager", "classncine_1_1_i_input_manager.html", null ],
    [ "ncine::IJobSystem", "classncine_1_1_i_job_system.html", [
      [ "ncine::NullJobSystem", "classncine_1_1_null_job_system.html", null ]
    ] ],
    [ "ncine::ILogger", "classncine_1_1_i_logger.html", [
      [ "ncine::NullLogger", "classncine_1_1_null_logger.html", null ]
    ] ],
    [ "nctl::integralConstant< T, v >", "structnctl_1_1integral_constant.html", [
      [ "nctl::isClass< T, typename >", "structnctl_1_1is_class.html", null ],
      [ "nctl::isDestructible< T, typename >", "structnctl_1_1is_destructible.html", null ],
      [ "nctl::isIntegral< T >", "structnctl_1_1is_integral.html", null ],
      [ "nctl::isIntegral< bool >", "structnctl_1_1is_integral_3_01bool_01_4.html", null ],
      [ "nctl::isIntegral< char >", "structnctl_1_1is_integral_3_01char_01_4.html", null ],
      [ "nctl::isIntegral< int >", "structnctl_1_1is_integral_3_01int_01_4.html", null ],
      [ "nctl::isIntegral< long >", "structnctl_1_1is_integral_3_01long_01_4.html", null ],
      [ "nctl::isIntegral< long long >", "structnctl_1_1is_integral_3_01long_01long_01_4.html", null ],
      [ "nctl::isIntegral< short int >", "structnctl_1_1is_integral_3_01short_01int_01_4.html", null ],
      [ "nctl::isIntegral< unsigned char >", "structnctl_1_1is_integral_3_01unsigned_01char_01_4.html", null ],
      [ "nctl::isIntegral< unsigned int >", "structnctl_1_1is_integral_3_01unsigned_01int_01_4.html", null ],
      [ "nctl::isIntegral< unsigned long >", "structnctl_1_1is_integral_3_01unsigned_01long_01_4.html", null ],
      [ "nctl::isIntegral< unsigned long long >", "structnctl_1_1is_integral_3_01unsigned_01long_01long_01_4.html", null ],
      [ "nctl::isIntegral< unsigned short int >", "structnctl_1_1is_integral_3_01unsigned_01short_01int_01_4.html", null ],
      [ "nctl::isSame< T, U >", "structnctl_1_1is_same.html", null ],
      [ "nctl::isSame< T, T >", "structnctl_1_1is_same_3_01_t_00_01_t_01_4.html", null ]
    ] ],
    [ "nctl::integralConstant< bool, !__is_union(T)>", "structnctl_1_1integral_constant.html", [
      [ "nctl::isClass< T, typename detail::voidType< int T::* >::type >", "structnctl_1_1is_class_3_01_t_00_01typename_01detail_1_1void_type_3_01int_01_t_1_1_5_01_4_1_1type_01_4.html", null ],
      [ "nctl::isDestructible< T, decltype(declVal< T & >().~T())>", "structnctl_1_1is_destructible_3_01_t_00_01decltype_07decl_val_3_01_t_01_6_01_4_07_08_8_0i_t_07_08_08_4.html", null ]
    ] ],
    [ "nctl::integralConstant< bool, __is_nothrow_constructible(T, Args...) >", "structnctl_1_1integral_constant.html", [
      [ "nctl::isNoThrowConstructible< T, Args >", "structnctl_1_1is_no_throw_constructible.html", null ]
    ] ],
    [ "nctl::MakeUniqueReturn< T[size], Deleter >::invalid", "structnctl_1_1_make_unique_return_3_01_t_0fsize_0e_00_01_deleter_01_4_1_1invalid.html", null ],
    [ "nctl::isConvertible< From, To >", "structnctl_1_1is_convertible.html", null ],
    [ "nctl::isCopyConstructible< T >", "structnctl_1_1is_copy_constructible.html", null ],
    [ "nctl::isEmpty< T >", "structnctl_1_1is_empty.html", null ],
    [ "nctl::IsEqualTo< T >", "classnctl_1_1_is_equal_to.html", null ],
    [ "nctl::IsGreaterThan< T >", "classnctl_1_1_is_greater_than.html", null ],
    [ "nctl::IsLessThan< T >", "classnctl_1_1_is_less_than.html", null ],
    [ "nctl::isLValueReference< T >", "structnctl_1_1is_l_value_reference.html", null ],
    [ "nctl::isLValueReference< T & >", "structnctl_1_1is_l_value_reference_3_01_t_01_6_01_4.html", null ],
    [ "nctl::isMoveConstructible< T >", "structnctl_1_1is_move_constructible.html", null ],
    [ "nctl::IsNotEqualTo< T >", "classnctl_1_1_is_not_equal_to.html", null ],
    [ "nctl::IsNotGreaterThan< T >", "classnctl_1_1_is_not_greater_than.html", null ],
    [ "nctl::IsNotLessThan< T >", "classnctl_1_1_is_not_less_than.html", null ],
    [ "nctl::detail::isTrivial< T >", "structnctl_1_1detail_1_1is_trivial.html", null ],
    [ "nctl::isTriviallyConstructible< T >", "structnctl_1_1is_trivially_constructible.html", null ],
    [ "nctl::isTriviallyCopyable< T >", "structnctl_1_1is_trivially_copyable.html", null ],
    [ "nctl::isTriviallyDestructible< T >", "structnctl_1_1is_trivially_destructible.html", null ],
    [ "nctl::IteratorTraits< Iterator >", "structnctl_1_1_iterator_traits.html", null ],
    [ "nctl::IteratorTraits< ArrayIterator >", "structnctl_1_1_iterator_traits.html", null ],
    [ "nctl::IteratorTraits< ArrayIterator< T, false > >", "structnctl_1_1_iterator_traits_3_01_array_iterator_3_01_t_00_01false_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< ArrayIterator< T, true > >", "structnctl_1_1_iterator_traits_3_01_array_iterator_3_01_t_00_01true_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< const T * >", "structnctl_1_1_iterator_traits_3_01const_01_t_01_5_01_4.html", null ],
    [ "nctl::IteratorTraits< HashMapIterator< K, T, HashFunc, false > >", "structnctl_1_1_iterator_traits_3_01_hash_map_iterator_3_01_k_00_01_t_00_01_hash_func_00_01false_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< HashMapIterator< K, T, HashFunc, true > >", "structnctl_1_1_iterator_traits_3_01_hash_map_iterator_3_01_k_00_01_t_00_01_hash_func_00_01true_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< HashMapListIterator< K, T, HashFunc, false > >", "structnctl_1_1_iterator_traits_3_01_hash_map_list_iterator_3_01_k_00_01_t_00_01_hash_func_00_01false_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< HashMapListIterator< K, T, HashFunc, true > >", "structnctl_1_1_iterator_traits_3_01_hash_map_list_iterator_3_01_k_00_01_t_00_01_hash_func_00_01true_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< HashSetIterator< K, HashFunc > >", "structnctl_1_1_iterator_traits_3_01_hash_set_iterator_3_01_k_00_01_hash_func_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< HashSetListIterator< K, HashFunc > >", "structnctl_1_1_iterator_traits_3_01_hash_set_list_iterator_3_01_k_00_01_hash_func_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< ListIterator< T, false > >", "structnctl_1_1_iterator_traits_3_01_list_iterator_3_01_t_00_01false_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< ListIterator< T, true > >", "structnctl_1_1_iterator_traits_3_01_list_iterator_3_01_t_00_01true_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< ReverseIterator< Iterator > >", "structnctl_1_1_iterator_traits_3_01_reverse_iterator_3_01_iterator_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< SparseSetIterator< T > >", "structnctl_1_1_iterator_traits_3_01_sparse_set_iterator_3_01_t_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< StaticHashMapIterator< K, T, HashFunc, Capacity, false > >", "structnctl_1_1_iterator_traits_3_01_static_hash_map_iterator_3_01_k_00_01_t_00_01_hash_func_00_01_capacity_00_01false_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< StaticHashMapIterator< K, T, HashFunc, Capacity, true > >", "structnctl_1_1_iterator_traits_3_01_static_hash_map_iterator_3_01_k_00_01_t_00_01_hash_func_00_01_capacity_00_01true_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< StaticHashSetIterator< K, HashFunc, Capacity > >", "structnctl_1_1_iterator_traits_3_01_static_hash_set_iterator_3_01_k_00_01_hash_func_00_01_capacity_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< StringIterator >", "structnctl_1_1_iterator_traits.html", null ],
    [ "nctl::IteratorTraits< StringIterator< false > >", "structnctl_1_1_iterator_traits_3_01_string_iterator_3_01false_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< StringIterator< true > >", "structnctl_1_1_iterator_traits_3_01_string_iterator_3_01true_01_4_01_4.html", null ],
    [ "nctl::IteratorTraits< T * >", "structnctl_1_1_iterator_traits_3_01_t_01_5_01_4.html", null ],
    [ "ITextureLoader", null, [
      [ "ncine::TextureLoaderImage", "classncine_1_1_texture_loader_image.html", null ]
    ] ],
    [ "nctl::deprecated::JenkinsHashFunc< K >", "classnctl_1_1deprecated_1_1_jenkins_hash_func.html", null ],
    [ "ncine::JobHandle", "classncine_1_1_job_handle.html", [
      [ "ncine::ScopedJobHandle", "classncine_1_1_scoped_job_handle.html", null ]
    ] ],
    [ "ncine::JobStatistics::JobPoolStats", "structncine_1_1_job_statistics_1_1_job_pool_stats.html", null ],
    [ "ncine::JobStatistics::JobQueueStats", "structncine_1_1_job_statistics_1_1_job_queue_stats.html", null ],
    [ "ncine::JobStatistics", "classncine_1_1_job_statistics.html", null ],
    [ "ncine::AppConfiguration::JobSystem", "structncine_1_1_app_configuration_1_1_job_system.html", null ],
    [ "ncine::JobStatistics::JobSystemStats", "structncine_1_1_job_statistics_1_1_job_system_stats.html", null ],
    [ "ncine::JobStatistics::JobSystemStatsHelper", "classncine_1_1_job_statistics_1_1_job_system_stats_helper.html", null ],
    [ "ncine::JoyAxisEvent", "classncine_1_1_joy_axis_event.html", null ],
    [ "ncine::JoyButtonEvent", "classncine_1_1_joy_button_event.html", null ],
    [ "ncine::JoyConnectionEvent", "classncine_1_1_joy_connection_event.html", null ],
    [ "ncine::JoyHatEvent", "classncine_1_1_joy_hat_event.html", null ],
    [ "ncine::JoyMappedAxisEvent", "classncine_1_1_joy_mapped_axis_event.html", null ],
    [ "ncine::JoyMappedButtonEvent", "classncine_1_1_joy_mapped_button_event.html", null ],
    [ "ncine::JoyMappedState", "classncine_1_1_joy_mapped_state.html", null ],
    [ "ncine::JoystickState", "classncine_1_1_joystick_state.html", null ],
    [ "ncine::KeyboardEvent", "classncine_1_1_keyboard_event.html", null ],
    [ "ncine::KeyboardState", "classncine_1_1_keyboard_state.html", null ],
    [ "nctl::detail::KeyBytes< K >", "structnctl_1_1detail_1_1_key_bytes.html", null ],
    [ "nctl::detail::KeyBytes< const char * >", "structnctl_1_1detail_1_1_key_bytes_3_01const_01char_01_5_01_4.html", null ],
    [ "nctl::detail::KeyBytes< String >", "structnctl_1_1detail_1_1_key_bytes_3_01_string_01_4.html", null ],
    [ "nctl::List< T >", "classnctl_1_1_list.html", null ],
    [ "nctl::List< Node >", "classnctl_1_1_list.html", null ],
    [ "nctl::ListIterator< T, IsConst >", "classnctl_1_1_list_iterator.html", null ],
    [ "ncine::AppConfiguration::Logging", "structncine_1_1_app_configuration_1_1_logging.html", null ],
    [ "ncine::LuaColorfUtils", "classncine_1_1_lua_colorf_utils.html", null ],
    [ "ncine::LuaColorUtils", "classncine_1_1_lua_color_utils.html", null ],
    [ "ncine::LuaIAppEventHandler", "classncine_1_1_lua_i_app_event_handler.html", null ],
    [ "ncine::LuaIInputEventHandler", "classncine_1_1_lua_i_input_event_handler.html", null ],
    [ "ncine::LuaRectUtils< T >", "classncine_1_1_lua_rect_utils.html", null ],
    [ "ncine::LuaStateManager", "classncine_1_1_lua_state_manager.html", null ],
    [ "ncine::LuaUntrackedUserData< T >", "classncine_1_1_lua_untracked_user_data.html", null ],
    [ "ncine::LuaVector2Utils< T >", "classncine_1_1_lua_vector2_utils.html", null ],
    [ "ncine::LuaVector3Utils< T >", "classncine_1_1_lua_vector3_utils.html", null ],
    [ "ncine::LuaVector4Utils< T >", "classncine_1_1_lua_vector4_utils.html", null ],
    [ "nctl::MakeUniqueReturn< T, Deleter >", "structnctl_1_1_make_unique_return.html", null ],
    [ "nctl::MakeUniqueReturn< T[], Deleter >", "structnctl_1_1_make_unique_return_3_01_t_0f_0e_00_01_deleter_01_4.html", null ],
    [ "nctl::MakeUniqueReturn< T[size], Deleter >", "structnctl_1_1_make_unique_return_3_01_t_0fsize_0e_00_01_deleter_01_4.html", null ],
    [ "ncine::Matrix4x4< T >", "classncine_1_1_matrix4x4.html", null ],
    [ "ncine::Matrix4x4< float >", "classncine_1_1_matrix4x4.html", null ],
    [ "nctl::ModuloHashFunc< K, Value >", "classnctl_1_1_modulo_hash_func.html", null ],
    [ "ncine::IGfxDevice::Monitor", "structncine_1_1_i_gfx_device_1_1_monitor.html", null ],
    [ "ncine::MouseEvent", "classncine_1_1_mouse_event.html", null ],
    [ "ncine::MouseState", "classncine_1_1_mouse_state.html", null ],
    [ "nctl::detail::MovableTag", "structnctl_1_1detail_1_1_movable_tag.html", null ],
    [ "nctl::detail::MoveOnlyTag", "structnctl_1_1detail_1_1_move_only_tag.html", null ],
    [ "nctl::Mul64To32Hash< K >", "classnctl_1_1_mul64_to32_hash.html", null ],
    [ "nctl::detail::NonMovableTag", "structnctl_1_1detail_1_1_non_movable_tag.html", null ],
    [ "ncine::NuklearContext", "classncine_1_1_nuklear_context.html", null ],
    [ "nctl::NullOptTag", "structnctl_1_1_null_opt_tag.html", null ],
    [ "ncine::Object", "classncine_1_1_object.html", [
      [ "ncine::AudioBuffer", "classncine_1_1_audio_buffer.html", null ],
      [ "ncine::Font", "classncine_1_1_font.html", null ],
      [ "ncine::IAudioPlayer", "classncine_1_1_i_audio_player.html", [
        [ "ncine::AudioBufferPlayer", "classncine_1_1_audio_buffer_player.html", null ],
        [ "ncine::AudioStreamPlayer", "classncine_1_1_audio_stream_player.html", null ]
      ] ],
      [ "ncine::SceneNode", "classncine_1_1_scene_node.html", [
        [ "ncine::DrawableNode", "classncine_1_1_drawable_node.html", [
          [ "ncine::BaseSprite", "classncine_1_1_base_sprite.html", [
            [ "ncine::MeshSprite", "classncine_1_1_mesh_sprite.html", null ],
            [ "ncine::Sprite", "classncine_1_1_sprite.html", [
              [ "ncine::AnimatedSprite", "classncine_1_1_animated_sprite.html", null ],
              [ "ncine::Particle", "classncine_1_1_particle.html", null ]
            ] ]
          ] ],
          [ "ncine::TextNode", "classncine_1_1_text_node.html", null ]
        ] ],
        [ "ncine::ParticleSystem", "classncine_1_1_particle_system.html", null ]
      ] ],
      [ "ncine::Shader", "classncine_1_1_shader.html", null ],
      [ "ncine::Texture", "classncine_1_1_texture.html", null ]
    ] ],
    [ "nctl::detail::ObjectPolicyTag< T >", "structnctl_1_1detail_1_1_object_policy_tag.html", null ],
    [ "ncine::AppConfiguration::Graphics::OpenGL", "structncine_1_1_app_configuration_1_1_graphics_1_1_open_g_l.html", null ],
    [ "ncine::AppConfiguration::Graphics::OpenGLCapabilities", "structncine_1_1_app_configuration_1_1_graphics_1_1_open_g_l_capabilities.html", null ],
    [ "ncine::IFile::OpenMode", "structncine_1_1_i_file_1_1_open_mode.html", null ],
    [ "nctl::Optional< T >", "classnctl_1_1_optional.html", null ],
    [ "nctl::Pair< T1, T2 >", "structnctl_1_1_pair.html", null ],
    [ "nctl::detail::PairImpl< T1, T2, value >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< char *, DefaultDelete< char > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< crashpad::CrashpadClient *, DefaultDelete< crashpad::CrashpadClient > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< FontGlyph *, DefaultDelete< FontGlyph > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< FrameTimer *, DefaultDelete< FrameTimer > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< GLFramebufferObject *, DefaultDelete< GLFramebufferObject > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< GLShaderProgram *, DefaultDelete< GLShaderProgram > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< GLTexture *, DefaultDelete< GLTexture > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< IAudioReader *, DefaultDelete< IAudioReader > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< ncine::IAppEventHandler *, DefaultDelete< ncine::IAppEventHandler > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< ncine::IAudioDevice *, DefaultDelete< ncine::IAudioDevice > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< ncine::IDebugOverlay *, DefaultDelete< ncine::IDebugOverlay > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< ncine::IGfxCapabilities *, DefaultDelete< ncine::IGfxCapabilities > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< ncine::IGfxDevice *, DefaultDelete< ncine::IGfxDevice > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< ncine::IIndexer *, DefaultDelete< ncine::IIndexer > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< ncine::IInputManager *, DefaultDelete< ncine::IInputManager > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< ncine::IJobSystem *, DefaultDelete< ncine::IJobSystem > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< ncine::ILogger *, DefaultDelete< ncine::ILogger > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< ncine::Particle *, DefaultDelete< ncine::Particle > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< ncine::ParticleAffector *, DefaultDelete< ncine::ParticleAffector > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< ncine::Texture *, DefaultDelete< ncine::Texture > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< RenderCommand *, DefaultDelete< RenderCommand > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< RenderQueue *, DefaultDelete< RenderQueue > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< T *, DefaultDelete< T > >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< T *, Deleter >", "structnctl_1_1detail_1_1_pair_impl.html", null ],
    [ "nctl::detail::PairImpl< T1, T2, true >", "structnctl_1_1detail_1_1_pair_impl_3_01_t1_00_01_t2_00_01true_01_4.html", null ],
    [ "ncine::parallelForJobData< T, S >", "structncine_1_1parallel_for_job_data.html", null ],
    [ "ncine::ParticleAffector", "classncine_1_1_particle_affector.html", [
      [ "ncine::ColorAffector", "classncine_1_1_color_affector.html", null ],
      [ "ncine::PositionAffector", "classncine_1_1_position_affector.html", null ],
      [ "ncine::RotationAffector", "classncine_1_1_rotation_affector.html", null ],
      [ "ncine::SizeAffector", "classncine_1_1_size_affector.html", null ],
      [ "ncine::VelocityAffector", "classncine_1_1_velocity_affector.html", null ]
    ] ],
    [ "ncine::ParticleInitializer", "structncine_1_1_particle_initializer.html", null ],
    [ "ncine::AudioEffectProperties::PitchShifterProperties", "structncine_1_1_audio_effect_properties_1_1_pitch_shifter_properties.html", null ],
    [ "ncine::ImageSaverPng::PngProperties", "structncine_1_1_image_saver_png_1_1_png_properties.html", null ],
    [ "ncine::TouchEvent::Pointer", "structncine_1_1_touch_event_1_1_pointer.html", null ],
    [ "ncine::PositionAffector::PositionStep", "structncine_1_1_position_affector_1_1_position_step.html", null ],
    [ "ncine::Camera::ProjectionValues", "structncine_1_1_camera_1_1_projection_values.html", null ],
    [ "ncine::AudioFilter::Properties", "structncine_1_1_audio_filter_1_1_properties.html", null ],
    [ "ncine::IImageSaver::Properties", "structncine_1_1_i_image_saver_1_1_properties.html", null ],
    [ "QOpenGLWidget", null, [
      [ "ncine::Qt5Widget", "classncine_1_1_qt5_widget.html", null ]
    ] ],
    [ "ncine::Quaternion< T >", "classncine_1_1_quaternion.html", null ],
    [ "ncine::Random", "classncine_1_1_random.html", null ],
    [ "ncine::Rect< T >", "classncine_1_1_rect.html", null ],
    [ "ncine::Rect< float >", "classncine_1_1_rect.html", null ],
    [ "ncine::Rect< int >", "classncine_1_1_rect.html", null ],
    [ "ncine::RectAnimation", "classncine_1_1_rect_animation.html", null ],
    [ "nctl::removeConst< T >", "structnctl_1_1remove_const.html", null ],
    [ "nctl::removeConst< const T >", "structnctl_1_1remove_const_3_01const_01_t_01_4.html", null ],
    [ "nctl::removeCv< T >", "structnctl_1_1remove_cv.html", null ],
    [ "nctl::removeExtent< T >", "structnctl_1_1remove_extent.html", null ],
    [ "nctl::removeExtent< T[]>", "structnctl_1_1remove_extent_3_01_t_0f_0e_4.html", null ],
    [ "nctl::removeExtent< T[N]>", "structnctl_1_1remove_extent_3_01_t_0f_n_0e_4.html", null ],
    [ "nctl::removeReference< T >", "structnctl_1_1remove_reference.html", null ],
    [ "nctl::removeReference< T & >", "structnctl_1_1remove_reference_3_01_t_01_6_01_4.html", null ],
    [ "nctl::removeReference< T && >", "structnctl_1_1remove_reference_3_01_t_01_6_6_01_4.html", null ],
    [ "nctl::removeVolatile< T >", "structnctl_1_1remove_volatile.html", null ],
    [ "nctl::removeVolatile< volatile T >", "structnctl_1_1remove_volatile_3_01volatile_01_t_01_4.html", null ],
    [ "ncine::RenderDocCapture", "classncine_1_1_render_doc_capture.html", null ],
    [ "ncine::Application::RenderingSettings", "structncine_1_1_application_1_1_rendering_settings.html", null ],
    [ "ncine::AudioEffectProperties::ReverbProperties", "structncine_1_1_audio_effect_properties_1_1_reverb_properties.html", null ],
    [ "nctl::ReverseIterator< Iterator >", "classnctl_1_1_reverse_iterator.html", null ],
    [ "nctl::ReversionWrapper< T >", "structnctl_1_1_reversion_wrapper.html", null ],
    [ "ncine::AudioEffectProperties::RingModulatorProperties", "structncine_1_1_audio_effect_properties_1_1_ring_modulator_properties.html", null ],
    [ "ncine::RotationAffector::RotationStep", "structncine_1_1_rotation_affector_1_1_rotation_step.html", null ],
    [ "ncine::LuaUtils::RunInfo", "classncine_1_1_lua_utils_1_1_run_info.html", null ],
    [ "nctl::deprecated::SaxHashFunc< K >", "classnctl_1_1deprecated_1_1_sax_hash_func.html", null ],
    [ "ncine::ScrollEvent", "classncine_1_1_scroll_event.html", null ],
    [ "ncine::ServiceLocator", "classncine_1_1_service_locator.html", null ],
    [ "ncine::ShaderState", "classncine_1_1_shader_state.html", null ],
    [ "nctl::SharedPtr< T >", "classnctl_1_1_shared_ptr.html", null ],
    [ "ncine::SizeAffector::SizeStep", "structncine_1_1_size_affector_1_1_size_step.html", null ],
    [ "nctl::Span< T >", "classnctl_1_1_span.html", null ],
    [ "nctl::SparseSet< T >", "classnctl_1_1_sparse_set.html", null ],
    [ "nctl::SparseSetIterator< T >", "classnctl_1_1_sparse_set_iterator.html", null ],
    [ "ncine::LuaStateManager::StateToManager", "structncine_1_1_lua_state_manager_1_1_state_to_manager.html", null ],
    [ "nctl::StaticArray< T, Capacity >", "classnctl_1_1_static_array.html", null ],
    [ "nctl::StaticArray< unsigned int, NumBuffers >", "classnctl_1_1_static_array.html", null ],
    [ "nctl::StaticHashMap< K, T, Capacity, HashFunc >", "classnctl_1_1_static_hash_map.html", null ],
    [ "nctl::StaticHashMapHelperTraits< K, T, HashFunc, Capacity, IsConst >", "structnctl_1_1_static_hash_map_helper_traits.html", null ],
    [ "nctl::StaticHashMapHelperTraits< K, T, HashFunc, Capacity, false >", "structnctl_1_1_static_hash_map_helper_traits_3_01_k_00_01_t_00_01_hash_func_00_01_capacity_00_01false_01_4.html", null ],
    [ "nctl::StaticHashMapHelperTraits< K, T, HashFunc, Capacity, true >", "structnctl_1_1_static_hash_map_helper_traits_3_01_k_00_01_t_00_01_hash_func_00_01_capacity_00_01true_01_4.html", null ],
    [ "nctl::StaticHashMapIterator< K, T, HashFunc, Capacity, IsConst >", "classnctl_1_1_static_hash_map_iterator.html", null ],
    [ "nctl::StaticHashSet< K, Capacity, HashFunc >", "classnctl_1_1_static_hash_set.html", null ],
    [ "nctl::StaticHashSetHelperTraits< K, HashFunc, Capacity >", "structnctl_1_1_static_hash_set_helper_traits.html", null ],
    [ "nctl::StaticHashSetIterator< K, HashFunc, Capacity >", "classnctl_1_1_static_hash_set_iterator.html", null ],
    [ "nctl::StaticString< Capacity >", "classnctl_1_1_static_string.html", null ],
    [ "nctl::StaticString< MaxNameLength >", "classnctl_1_1_static_string.html", null ],
    [ "ncine::Hash64::Statistics", "structncine_1_1_hash64_1_1_statistics.html", null ],
    [ "ncine::StorageAlign< T >", "structncine_1_1_storage_align.html", null ],
    [ "ncine::StorageAlign< float >", "structncine_1_1_storage_align_3_01float_01_4.html", null ],
    [ "nctl::String", "classnctl_1_1_string.html", null ],
    [ "nctl::StringIterator< IsConst >", "classnctl_1_1_string_iterator.html", null ],
    [ "nctl::StringView", "classnctl_1_1_string_view.html", null ],
    [ "ncine::TextInputEvent", "classncine_1_1_text_input_event.html", null ],
    [ "ncine::Timer", "classncine_1_1_timer.html", null ],
    [ "ncine::TimeStamp", "classncine_1_1_time_stamp.html", null ],
    [ "ncine::Application::Timings", "structncine_1_1_application_1_1_timings.html", null ],
    [ "ncine::TouchEvent", "classncine_1_1_touch_event.html", null ],
    [ "nctl::detail::TrivialTag", "structnctl_1_1detail_1_1_trivial_tag.html", null ],
    [ "decltypedetail::tryAddLValueReference", null, [
      [ "nctl::addLValueReference< T >", "structnctl_1_1add_l_value_reference.html", null ]
    ] ],
    [ "decltypedetail::tryAddRValueReference", null, [
      [ "nctl::addRValueReference< T >", "structnctl_1_1add_r_value_reference.html", null ]
    ] ],
    [ "nctl::detail::typeIdentity< T >", "structnctl_1_1detail_1_1type_identity.html", null ],
    [ "nctl::UniquePtr< T, Deleter >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< char[]>", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< crashpad::CrashpadClient >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< FontGlyph[]>", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< FrameTimer >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< GLFramebufferObject >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< GLShaderProgram >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< GLTexture >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< IAudioReader >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< ncine::IAppEventHandler >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< ncine::IAudioDevice >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< ncine::IDebugOverlay >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< ncine::IGfxCapabilities >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< ncine::IGfxDevice >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< ncine::IIndexer >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< ncine::IInputManager >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< ncine::IJobSystem >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< ncine::ILogger >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< ncine::Particle >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< ncine::ParticleAffector >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< ncine::Texture >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< RenderCommand >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< RenderQueue >", "classnctl_1_1_unique_ptr.html", null ],
    [ "nctl::UniquePtr< T[], Deleter >", "classnctl_1_1_unique_ptr_3_01_t_0f_0e_00_01_deleter_01_4.html", null ],
    [ "ncine::Vector2< T >", "classncine_1_1_vector2.html", null ],
    [ "ncine::Vector2< float >", "classncine_1_1_vector2.html", null ],
    [ "ncine::Vector2< int >", "classncine_1_1_vector2.html", null ],
    [ "ncine::Vector3< T >", "classncine_1_1_vector3.html", null ],
    [ "ncine::Vector3< float >", "classncine_1_1_vector3.html", null ],
    [ "ncine::Vector4< T >", "classncine_1_1_vector4.html", null ],
    [ "ncine::Vector4< float >", "classncine_1_1_vector4.html", null ],
    [ "ncine::VelocityAffector::VelocityStep", "structncine_1_1_velocity_affector_1_1_velocity_step.html", null ],
    [ "ncine::MeshSprite::Vertex", "structncine_1_1_mesh_sprite_1_1_vertex.html", null ],
    [ "ncine::MeshSprite::VertexNoTexture", "structncine_1_1_mesh_sprite_1_1_vertex_no_texture.html", null ],
    [ "ncine::IGfxDevice::VideoMode", "structncine_1_1_i_gfx_device_1_1_video_mode.html", null ],
    [ "ncine::Viewport", "classncine_1_1_viewport.html", null ],
    [ "ncine::Camera::ViewValues", "structncine_1_1_camera_1_1_view_values.html", null ],
    [ "ncine::AudioEffectProperties::VocalMorpherProperties", "structncine_1_1_audio_effect_properties_1_1_vocal_morpher_properties.html", null ],
    [ "nctl::detail::voidType< class >", "structnctl_1_1detail_1_1void_type.html", null ],
    [ "ncine::ImageSaverWebP::WebPProperties", "structncine_1_1_image_saver_web_p_1_1_web_p_properties.html", null ],
    [ "ncine::AppConfiguration::Window", "structncine_1_1_app_configuration_1_1_window.html", null ],
    [ "ncine::IGfxDevice::WindowMode", "structncine_1_1_i_gfx_device_1_1_window_mode.html", null ]
];